<a href="https://colab.research.google.com/github/Zedbog/Data_science_course/blob/main/Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Regresja liniowa w scikit-learn



In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
# from google.colab import files
# uploaded = files.upload()

In [ ]:
data = pd.read_csv('/content/drive/My Drive/Machine_Learning/ex1data2.txt',header=None,names = ['meters','bedrooms','price'])

In [ ]:
data.head()

meters  bedrooms   price
0    2104         3  399900
1    1600         3  329900
2    2400         3  369000
3    1416         2  232000
4    3000         4  539900

In [ ]:
X = data[['meters']]
y = data[['price']]

In [ ]:
X.values[:5]

array([[2104],
       [1600],
       [2400],
       [1416],
       [3000]])

In [ ]:
y.values[:5]

array([[399900],
       [329900],
       [369000],
       [232000],
       [539900]])

In [ ]:
model = LinearRegression()
model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
model.intercept_

array([71270.49244873])

In [ ]:
model.coef_

array([[134.52528772]])

In [ ]:
predict_data = np.array([[3200], [3720]])
predict_data

array([[3200],
       [3720]])

In [ ]:
model.predict(predict_data)

array([[501751.4131535 ],
       [571704.56276803]])

# Regresja liniowa wielu zmiennych w scikit-learn

In [ ]:
x = data[['meters', 'bedrooms']]
y = data[['price']]

In [ ]:
model = LinearRegression()
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
model.intercept_

array([89597.9095428])

In [ ]:
model.coef_

array([[  139.21067402, -8738.01911233]])

In [ ]:
predict_data_with_bedrooms = np.array([[3200, 3], [3720, 2]])
predict_data_with_bedrooms

array([[3200,    3],
       [3720,    2]])

In [ ]:
model.predict(predict_data_with_bedrooms)

array([[508858.00906222],
       [589985.57866371]])

#Regresja wielomianowa w scikit-learn

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
poly = PolynomialFeatures(degree=3)
X_poly = poly.fit_transform(X)

In [ ]:
X_poly[:5]

array([[1.00000000e+00, 2.10400000e+03, 4.42681600e+06, 9.31402086e+09],
       [1.00000000e+00, 1.60000000e+03, 2.56000000e+06, 4.09600000e+09],
       [1.00000000e+00, 2.40000000e+03, 5.76000000e+06, 1.38240000e+10],
       [1.00000000e+00, 1.41600000e+03, 2.00505600e+06, 2.83915930e+09],
       [1.00000000e+00, 3.00000000e+03, 9.00000000e+06, 2.70000000e+10]])

In [ ]:
model = LinearRegression()
model.fit(X_poly, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
model.intercept_

array([236407.03585232])

In [ ]:
model.coef_

array([[ 0.00000000e+00, -1.07855433e+02,  1.06190390e-01,
        -1.38299983e-05]])

In [ ]:
predict_data = np.array([[3200], [3720]])
predict_data

array([[3200],
       [3720]])

In [ ]:
predict_data_poly = poly.transform(predict_data)

In [ ]:
predict_data_poly

array([[1.0000000e+00, 3.2000000e+03, 1.0240000e+07, 3.2768000e+10],
       [1.0000000e+00, 3.7200000e+03, 1.3838400e+07, 5.1478848e+10]])

In [ ]:
model.predict(predict_data_poly)

array([[525477.86332531],
       [592737.54295217]])

In [ ]:
model.intercept_

array([236407.03585232])

#Regresja wielomianowa z wieloma zmiennymi 

In [ ]:
x_poly = poly.fit_transform(x)

In [ ]:
x_poly[:5]

array([[1.00000000e+00, 2.10400000e+03, 3.00000000e+00, 4.42681600e+06,
        6.31200000e+03, 9.00000000e+00, 9.31402086e+09, 1.32804480e+07,
        1.89360000e+04, 2.70000000e+01],
       [1.00000000e+00, 1.60000000e+03, 3.00000000e+00, 2.56000000e+06,
        4.80000000e+03, 9.00000000e+00, 4.09600000e+09, 7.68000000e+06,
        1.44000000e+04, 2.70000000e+01],
       [1.00000000e+00, 2.40000000e+03, 3.00000000e+00, 5.76000000e+06,
        7.20000000e+03, 9.00000000e+00, 1.38240000e+10, 1.72800000e+07,
        2.16000000e+04, 2.70000000e+01],
       [1.00000000e+00, 1.41600000e+03, 2.00000000e+00, 2.00505600e+06,
        2.83200000e+03, 4.00000000e+00, 2.83915930e+09, 4.01011200e+06,
        5.66400000e+03, 8.00000000e+00],
       [1.00000000e+00, 3.00000000e+03, 4.00000000e+00, 9.00000000e+06,
        1.20000000e+04, 1.60000000e+01, 2.70000000e+10, 3.60000000e+07,
        4.80000000e+04, 6.40000000e+01]])

In [ ]:
model.fit(x_poly, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
model.intercept_

array([-22271.37645458])

In [ ]:
model.coef_

array([[ 0.00000000e+00,  3.91558122e+01,  1.54862068e+05,
         2.67038211e-01, -3.26702734e+02,  6.67279964e+04,
        -2.16721404e-05, -3.85899101e-02,  8.36292254e+01,
        -2.78260510e+04]])

In [ ]:
predict_data_with_bedrooms_poly = poly.transform(predict_data_with_bedrooms)

In [ ]:
predict_data_with_bedrooms_poly

array([[1.0000000e+00, 3.2000000e+03, 3.0000000e+00, 1.0240000e+07,
        9.6000000e+03, 9.0000000e+00, 3.2768000e+10, 3.0720000e+07,
        2.8800000e+04, 2.7000000e+01],
       [1.0000000e+00, 3.7200000e+03, 2.0000000e+00, 1.3838400e+07,
        7.4400000e+03, 4.0000000e+00, 5.1478848e+10, 2.7676800e+07,
        1.4880000e+04, 8.0000000e+00]])

In [ ]:
model.predict(predict_data_with_bedrooms_poly)

array([[527873.99903645],
       [802830.01563471]])

#Drzewo decyzyjne

In [ ]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeRegressor

In [ ]:
X.values[:5]

array([[2104],
       [1600],
       [2400],
       [1416],
       [3000]])

In [ ]:
model = DecisionTreeRegressor()
model.fit(X, y)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [ ]:
predict_data

array([[3200],
       [3720]])

In [ ]:
model.predict(predict_data)

array([579900., 573900.])

modifukujemy parametry drzewa

In [ ]:
model = DecisionTreeRegressor(max_depth=5, min_samples_split=3)

In [ ]:
model.fit(X, y)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=5,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=3,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [ ]:
predict_data

array([[3200],
       [3720]])

In [ ]:
model.predict(predict_data)

array([576900., 576900.])

#Drzewo decyzyjne z wieloma zmiennymi

In [ ]:
x.values[:5]

array([[2104,    3],
       [1600,    3],
       [2400,    3],
       [1416,    2],
       [3000,    4]])

In [ ]:
model = DecisionTreeRegressor(max_depth=5, min_samples_split=3)
model.fit(x, y)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=5,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=3,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [ ]:
predict_data_with_bedrooms

array([[3200,    3],
       [3720,    2]])

In [ ]:
model.predict(predict_data_with_bedrooms)

array([576900., 576900.])

modyfikujemy parametry drzewa z wieloma zmiennymi

In [ ]:
model.predict(predict_data_with_bedrooms)

array([576900., 576900.])

#Wizualizacja danych

In [ ]:
from plotly.offline import iplot 

In [ ]:
data.bedrooms

0     3
1     3
2     3
3     2
4     4
5     4
6     3
7     3
8     3
9     3
10    4
11    3
12    3
13    5
14    3
15    4
16    2
17    3
18    4
19    4
20    3
21    2
22    3
23    4
24    3
25    3
26    3
27    3
28    3
29    3
30    2
31    1
32    4
33    3
34    4
35    3
36    3
37    4
38    4
39    4
40    2
41    3
42    4
43    3
44    2
45    4
46    3
Name: bedrooms, dtype: int64

In [ ]:
dane = [
        {
          'x': data.meters,
          'y': data.price,
          'mode': 'markers',
          'marker': {
              'color': data.bedrooms,
              # 'size': data.bedrooms,
              'showscale': True
          },
          'text': data.bedrooms
        }
]
iplot(dane)

#Metody oceny modelu

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x.values

array([[2104,    3],
       [1600,    3],
       [2400,    3],
       [1416,    2],
       [3000,    4],
       [1985,    4],
       [1534,    3],
       [1427,    3],
       [1380,    3],
       [1494,    3],
       [1940,    4],
       [2000,    3],
       [1890,    3],
       [4478,    5],
       [1268,    3],
       [2300,    4],
       [1320,    2],
       [1236,    3],
       [2609,    4],
       [3031,    4],
       [1767,    3],
       [1888,    2],
       [1604,    3],
       [1962,    4],
       [3890,    3],
       [1100,    3],
       [1458,    3],
       [2526,    3],
       [2200,    3],
       [2637,    3],
       [1839,    2],
       [1000,    1],
       [2040,    4],
       [3137,    3],
       [1811,    4],
       [1437,    3],
       [1239,    3],
       [2132,    4],
       [4215,    4],
       [2162,    4],
       [1664,    2],
       [2238,    3],
       [2567,    4],
       [1200,    3],
       [ 852,    2],
       [1852,    4],
       [1203,    3]])

podział na zbiór uczący i testowy

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
print(x.shape, y.shape)
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(47, 2) (47, 1)
(37, 2) (37, 1)
(10, 2) (10, 1)


podział na zbiór uczący z wydzielonym zbiorem walidacyjnym i zbiór testowy

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.25, random_state=1)

In [ ]:
print(x.shape, y.shape)
print(x_train.shape, y_train.shape)
print(x_val.shape, y_val.shape)
print(x_test.shape, y_test.shape)

(47, 2) (47, 1)
(27, 2) (27, 1)
(10, 2) (10, 1)
(10, 2) (10, 1)


Metoda kroswalidacji

In [ ]:
from sklearn.model_selection import KFold

In [ ]:
cv = KFold(n_splits=5, shuffle=True, random_state=42)

In [ ]:
for train, test in cv.split(x, y):
  x_train, y_train = x.iloc[train], y.iloc[test]
  x_test, y_test = x.iloc[test], y.iloc[test]
  print(x_train.shape, x_test.shape)

(37, 2) (10, 2)
(37, 2) (10, 2)
(38, 2) (9, 2)
(38, 2) (9, 2)
(38, 2) (9, 2)


walidacja krzyżowa leave-one-out

In [ ]:
from sklearn.model_selection import LeaveOneOut

In [ ]:
cv2_leave_one_out = LeaveOneOut()

In [ ]:
for train, test in cv2_leave_one_out.split(x, y):
  x_train, y_train = x.iloc[train], y.iloc[train]
  x_test, y_test = x.iloc[test], y.iloc[test]
  print(x_train.shape, x_test.shape)

(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)
(46, 2) (1, 2)


współczynnik R2 do oceny regresji

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [ ]:
model = LinearRegression()
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_predict = model.predict(x)

In [ ]:
print(y_predict)

[[356283.1103389 ]
 [286120.93063401]
 [397489.46984812]
 [269244.1857271 ]
 [472277.85514636]
 [330979.02101847]
 [276933.02614885]
 [262037.48402897]
 [255494.58235014]
 [271364.59918815]
 [324714.54068768]
 [341805.20024107]
 [326492.02609913]
 [669293.21223209]
 [239902.98686016]
 [374830.38333402]
 [255879.96102141]
 [235448.2452916 ]
 [417846.48160547]
 [476593.38604091]
 [309369.11319496]
 [334951.62386342]
 [286677.77333009]
 [327777.17551607]
 [604913.37413438]
 [216515.5936252 ]
 [266353.01492351]
 [415030.01477434]
 [369647.33504459]
 [430482.39959029]
 [328130.30083656]
 [220070.5644481 ]
 [338635.60808944]
 [500087.73659911]
 [306756.36373941]
 [263429.59076914]
 [235865.87731365]
 [351442.99009906]
 [641418.82407778]
 [355619.31031959]
 [303768.43288347]
 [374937.34065726]
 [411999.63329673]
 [230436.66102696]
 [190729.36558116]
 [312464.00137413]
 [230854.29304902]]


In [ ]:
print(y)

     price
0   399900
1   329900
2   369000
3   232000
4   539900
5   299900
6   314900
7   198999
8   212000
9   242500
10  239999
11  347000
12  329999
13  699900
14  259900
15  449900
16  299900
17  199900
18  499998
19  599000
20  252900
21  255000
22  242900
23  259900
24  573900
25  249900
26  464500
27  469000
28  475000
29  299900
30  349900
31  169900
32  314900
33  579900
34  285900
35  249900
36  229900
37  345000
38  549000
39  287000
40  368500
41  329900
42  314000
43  299000
44  179900
45  299900
46  239500


In [ ]:
r2_score(y, y_predict)

0.7329450180289143

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred = model.predict(x_test)

MAE - mean absolute error

In [ ]:
from sklearn.metrics import mean_absolute_error

In [ ]:
mean_absolute_error(y_test, y_pred)

72334.75360356673

MAPE - mean absolute percentage error - wymaga wersji 0.24 sklearn

In [ ]:
 import sklearn

In [ ]:
sklearn.__version__

'0.22.2.post1'

In [ ]:
# from sklearn.metrics import mean_absolute_percentage_error

MSE - mean squared error

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
mean_squared_error(y_test, y_pred)

8610424544.777674

RMSE - root mean squared eeror

In [ ]:
mean_squared_error(y_test, y_pred, squared=False)

92792.37331148327

Ocena dla różnych modeli

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import LeaveOneOut
from sklearn.metrics import r2_score

In [ ]:
#model liniowy 
model_linear = LinearRegression()
#model wielomianowy
model_linear_for_polynomial = LinearRegression()
poly = PolynomialFeatures(degree=3)
x_poly = poly.fit_transform(x)
#drzewo decyzyjne
model_tree = DecisionTreeRegressor(max_depth=5, min_samples_split=3,)

Model z podziałem na zbiór uczący i testowy

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
x_train_poly, x_test_poly, y_train_poly, y_test_poly = train_test_split(x_poly, y, test_size=0.2, random_state=42)

In [ ]:
model_linear.fit(x_train, y_train)
model_linear_for_polynomial.fit(x_train_poly, y_train_poly)
model_tree.fit(x_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=5,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=3,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [ ]:
y_predict_linear = model_linear.predict(x_test)
y_predict_polynomial = model_linear_for_polynomial.predict(x_test_poly)
y_predict_tree = model_tree.predict(x_test)

In [ ]:
print(f'R2 for linear: {r2_score(y_test, y_predict_linear)}')
print(f'R2 for polynomial: {r2_score(y_test, y_predict_polynomial)}')
print(f'R2 for tree: {r2_score(y_test, y_predict_tree)}')

R2 for linear: 0.514884881274144
R2 for polynomial: 0.37098999617945505
R2 for tree: 0.48923824444119046


Model z podziałem na zbiór uczący, walidacyjny i testowy

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
x_train_poly, x_test_poly, y_train_poly, y_test_poly = train_test_split(x_poly, y, test_size=0.2, random_state=42)
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.25, random_state=2)
x_train_poly, x_val_poly, y_train_poly, y_val_poly = train_test_split(x_train_poly, y_train_poly, test_size=0.25, random_state=2)

In [ ]:
model_linear.fit(x_train, y_train)
model_linear_for_polynomial.fit(x_train_poly, y_train_poly)
model_tree.fit(x_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=5,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=3,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [ ]:
y_predict_linear_val = model_linear.predict(x_val)
y_predict_polynomial_val = model_linear_for_polynomial.predict(x_val_poly)
y_predict_tree_val = model_tree.predict(x_val)

In [ ]:
print(f'R2 for linear dla walidacyjnych: {r2_score(y_test, y_predict_linear_val)}')
print(f'R2 for polynomial dla walidacyjnych: {r2_score(y_test, y_predict_polynomial_val)}')
print(f'R2 for tree dla walidacyjnych: {r2_score(y_test, y_predict_tree_val)}')

R2 for linear dla walidacyjnych: -0.8770699525698205
R2 for polynomial dla walidacyjnych: -1.0399736901677699
R2 for tree dla walidacyjnych: -1.3707618980174257


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=3)
x_train_poly, x_test_poly, y_train_poly, y_test_poly = train_test_split(x_poly, y, test_size=0.2, random_state=3)

In [ ]:
model_linear.fit(x_train, y_train)
model_linear_for_polynomial.fit(x_train_poly, y_train_poly)
model_tree.fit(x_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=5,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=3,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [ ]:
y_predict_linear = model_linear.predict(x_test)
y_predict_polynomial = model_linear_for_polynomial.predict(x_test_poly)
y_predict_tree = model_tree.predict(x_test)

In [ ]:
print(f'R2 for linear: {r2_score(y_test, y_predict_linear)}')
print(f'R2 for polynomial: {r2_score(y_test, y_predict_polynomial)}')
print(f'R2 for tree: {r2_score(y_test, y_predict_tree)}')

R2 for linear: 0.7688357973922066
R2 for polynomial: 0.7746556177998204
R2 for tree: -0.517702241548528


Model metodą kroswalidacji

In [ ]:
cv = KFold(n_splits=5, shuffle=True, random_state=42)
for train, test in cv.split(x, y):
  x_train, y_train = x.iloc[train], y.iloc[train]
  x_test, y_test = x.iloc[test], y.iloc[test]

In [ ]:
#dla wielomianu
cv_poly = KFold(n_splits=5, shuffle=True, random_state=42)
for train, test in cv_poly.split(x_poly, y):
  x_train_poly, y_train_poly = x.iloc[train], y.iloc[train]
  x_test_poly, y_test_poly = x.iloc[test], y.iloc[test]

In [ ]:
x_train.shape

(38, 2)

In [ ]:
y_train.shape

(38, 1)

In [ ]:
x_test.shape

(9, 2)

In [ ]:
y_test.shape

(9, 1)

In [ ]:
model_linear.fit(x_train, y_train)
model_linear_for_polynomial.fit(x_train_poly, y_train_poly)
model_tree.fit(x_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=5,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=3,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [ ]:
y_predict_linear = model_linear.predict(x_test)
y_predict_polynomial = model_linear_for_polynomial.predict(x_test_poly)
y_predict_tree = model_tree.predict(x_test)

In [ ]:
print(f'R2 for linear: {r2_score(y_test, y_predict_linear)}')
print(f'R2 for polynomial: {r2_score(y_test, y_predict_polynomial)}')
print(f'R2 for tree: {r2_score(y_test, y_predict_tree)}')

R2 for linear: 0.6533605489595493
R2 for polynomial: 0.6533605489595493
R2 for tree: 0.19412938199483276


model z walidacją krzyżową leave-one-out

In [ ]:
cv2_leave_one_out = LeaveOneOut()

In [ ]:
for train, test in cv2_leave_one_out.split(x, y):
  x_train, y_train = x.iloc[train], y.iloc[train]
  x_test, y_test = x.iloc[test], y.iloc[test]

In [ ]:
cv2_leave_one_out_poly = LeaveOneOut()

In [ ]:
for train, test in cv2_leave_one_out_poly.split(x_poly, y):
  x_train_poly, y_train_poly = x.iloc[train], y.iloc[train]
  x_test_poly, y_test_poly = x.iloc[test], y.iloc[test]

In [ ]:
model_linear.fit(x_train, y_train)
model_linear_for_polynomial.fit(x_train_poly, y_train_poly)
model_tree.fit(x_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=5,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=3,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [ ]:
x_train_poly.shape

(46, 2)

In [ ]:
y_train.shape

(46, 1)

In [ ]:
y_test.shape

(1, 1)

In [ ]:
y_predict_linear = model_linear.predict(x_test)
y_predict_polynomial = model_linear_for_polynomial.predict(x_test_poly)
y_predict_tree = model_tree.predict(x_test)

In [ ]:
print(f'R2 for linear dla leave-one-out: {r2_score(y_test, y_predict_linear)}')
print(f'R2 for polynomial dla leave-one-out: {r2_score(y_test, y_predict_polynomial)}')
print(f'R2 for tree dla leave-one-out: {r2_score(y_test, y_predict_tree)}')

R2 for linear dla leave-one-out: nan
R2 for polynomial dla leave-one-out: nan
R2 for tree dla leave-one-out: nan


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_regression.py:582: UndefinedMetricWarning:

R^2 score is not well-defined with less than two samples.

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_regression.py:582: UndefinedMetricWarning:

R^2 score is not well-defined with less than two samples.

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_regression.py:582: UndefinedMetricWarning:

R^2 score is not well-defined with less than two samples.

